version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/.github/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 7 *"
    assignees:
      - Gustry

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 7 *"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 7 *"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 7 *"
    assignees:
      - Gustry
