name: Release 🚀

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Changelog
        id: changelog
        uses: 3liz/changelog-release@0.4.0

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.18.0
        with:
          body: ${{ steps.changelog.outputs.markdown }}
          token: ${{ secrets.BOT_HUB_TOKEN }}
